version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    tty: true
    volumes:
      - ./:/go/src/app
    ports:
      - 50051:50051
    command: "go run ./pkg/server/server.go"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  envoy:
    build:
      context: ./proxy
    container_name: envoy
    ports:
      - 8080:8080