#  https://dev.classmethod.jp/articles/codebuild_envset_pipeline/
version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "StartBuild CODEBUILD_SOURCE_VERSION = ${CODEBUILD_SOURCE_VERSION}"
      - ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - AWS_ACCOOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${AWS_ACCOOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/attendance-management-backend
    pre_build:
      commands:
        - echo Pre-Build started on `date`
        - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
        - DATEYMD=$(date "+%Y%m%dT%H%M")