AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # ------------------------------------------------------------#
  #  LoadBalancer
  # ------------------------------------------------------------#
  InternetALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: !Sub
        - ${ProjectPrefixOutput}-alb
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      Subnets:
        - !ImportValue PublicSubnetAOutput
        - !ImportValue PublicSubnetCOutput
      SecurityGroups:
        - !ImportValue ALBSecurityGroupOutput

  # ------------------------------------------------------------#
  #  TargetGroup
  # ------------------------------------------------------------#
  ECSTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      VpcId: !ImportValue VPCOutput
      Name: !Sub
        - ${ProjectPrefixOutput}-ecs-tg
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      Protocol: HTTP
      Port: 80
      TargetType: ip

  # ------------------------------------------------------------#
  #  Listener
  # ------------------------------------------------------------#
  InternetALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 403
            MessageBody: Not authorized Access.
            ContentType: text/plain
      LoadBalancerArn: !Ref InternetALB
      Port: 80
      Protocol: HTTP

  # ------------------------------------------------------------#
  #  ListenerRule
  # ------------------------------------------------------------#
  InternetALBListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - TargetGroupArn: !Ref ECSTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "*"
      ListenerArn: !Ref InternetALBListener
      Priority: 1