AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub
        - ${ProjectPrefixOutput}-alb
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      Subnets:
        - !ImportValue PublicSubnetAOutput
        - !ImportValue PublicSubnetCOutput
      SecurityGroups:
        - !ImportValue ALBSecurityGroupOutput
