AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # ------------------------------------------------------------#
  # ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub
        - ${ProjectPrefixOutput}-cluster
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }

  # ------------------------------------------------------------#
  #  ECS Task Execution Role
  # ------------------------------------------------------------#
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - ${ProjectPrefixOutput}-ECSTaskExecutionRole
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
