AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # ------------------------------------------------------------#
  # ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub
        - ${ProjectPrefixOutput}-cluster
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }

  # ------------------------------------------------------------#
  #  ECS LogGroup
  # ------------------------------------------------------------#
  EnvoyTaskLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub
        - /ecs/logs/${ProjectPrefixOutput}-envoy
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }

  BackendTaskLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub
        - /ecs/logs/${ProjectPrefixOutput}-backend
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }

  # ------------------------------------------------------------#
  #  ECS Task Execution Role
  # ------------------------------------------------------------#
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - ${ProjectPrefixOutput}-ECSTaskExecutionRole
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ------------------------------------------------------------#
  #  ECS TaskDefinition
  #  TODO アプリImageのバージョンは自動デプロイのために動的にする必要がある
  # ------------------------------------------------------------#
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Memory: 512
      Cpu: 256
      NetworkMode: awsvpc
      Family: !Sub
        - ${ProjectPrefixOutput}-backend
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub
          - ${ProjectPrefixOutput}-envoy
          - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
          Image: !Sub
            - ${EnvoyRepositoryURIOutput}:v1.15-latest
            - EnvoyRepositoryURIOutput: { 'Fn::ImportValue': EnvoyRepositoryURIOutput }
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref EnvoyTaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !ImportValue ProjectPrefixOutput
          PortMappings:
            - HostPort: 8080
              Protocol: tcp
              ContainerPort: 8080
        - Name: !Sub
            - ${ProjectPrefixOutput}-backend
            - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
          # TODO タグが更新されていくので、ここは要修正
          Image: 992107678838.dkr.ecr.ap-northeast-1.amazonaws.com/attendance-management-backend:20210815T0109
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendTaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !ImportValue ProjectPrefixOutput
          PortMappings:
            - HostPort: 50051
              Protocol: tcp
              ContainerPort: 50051

  FargateService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Sub
        - ${ProjectPrefixOutput}-backend-service
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition
      LoadBalancers:
        - TargetGroupArn: !ImportValue ECSTargetGroupOutput
          ContainerPort: 8080
          ContainerName: !Sub
            - ${ProjectPrefixOutput}-envoy
            - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !ImportValue ALBSecurityGroupOutput
          Subnets:
            - !ImportValue PublicSubnetAOutput
            - !ImportValue PublicSubnetCOutput
