AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # ------------------------------------------------------------#
  # ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub
        - ${ProjectPrefixOutput}-cluster
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
