AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # ------------------------------------------------------------#
  # ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub
        - ${ProjectPrefixOutput}-cluster
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }

  # ------------------------------------------------------------#
  #  ECS Task Execution Role
  # ------------------------------------------------------------#
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - ${ProjectPrefixOutput}-ECSTaskExecutionRole
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ------------------------------------------------------------#
  #  ECS TaskDefinition
  #  TODO アプリImageのバージョンは自動デプロイのために動的にする必要がある
  # ------------------------------------------------------------#
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Memory: 512
      Cpu: 256
      Family: !Sub
        - ${ProjectPrefixOutput}-backend
        - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
      ContainerDefinitions:
        - Name: !Sub
          - ${ProjectPrefixOutput}-envoy
          - ProjectPrefixOutput: { 'Fn::ImportValue': ProjectPrefixOutput }
          Image: !Sub
            - ${EnvoyRepositoryURIOutput}:v1.15-latest
            - EnvoyRepositoryURIOutput: { 'Fn::ImportValue': EnvoyRepositoryURIOutput }