AWSTemplateFormatVersion: 2010-09-09

# 各種リソース
Resources:
  UsersPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: UsersPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'iam:PutUserPolicy'
              - 'iam:GetRole'
              - 'iam:DeleteRole'
              - 'iam:CreateRole'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:PassRole'
              - 'iam:CreateServiceLinkedRole'
              - 's3:CreateBucket'
              - 's3:PutBucketPublicAccessBlock'
              - 's3:DeleteBucket'
              - 'ec2:CreateVpc'
              - 'ec2:DeleteVpc'
              - 'ec2:DescribeVpcs'
              - 'ec2:ModifyVpcAttribute'
              - 'ec2:createTags'
              - 'ec2:CreateInternetGateway'
              - 'ec2:DescribeInternetGateways'
              - 'ec2:DeleteInternetGateway'
              - 'ec2:AttachInternetGateway'
              - 'ec2:CreateSubnet'
              - 'ec2:DeleteSubnet'
              - 'ec2:DescribeSubnets'
              - 'ec2:CreateRouteTable'
              - 'ec2:DeleteRouteTable'
              - 'ec2:DescribeRouteTable'
              - 'ec2:DescribeRouteTables'
              - 'ec2:CreateRoute'
              - 'ec2:DeleteRoute'
              - 'ec2:DescribeRoute'
              - 'ec2:AssociateRouteTable'
              - 'ec2:DisassociateRouteTable'
              - 'ec2:ReplaceRouteTableAssociation'
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:RevokeSecurityGroupIngress'
              - 'elasticloadbalancing:DescribeLoadBalancers'
              - 'elasticloadbalancing:CreateLoadBalancer'
              - 'elasticloadbalancing:DeleteLoadBalancer'
              - 'elasticloadbalancing:SetSecurityGroups'
              - 'ecr:SetRepositoryPolicy'
              - 'ecr:CreateRepository'
              - 'ecr:DeleteRepository'
              - 'ecr:GetAuthorizationToken'
              - 'codestar-connections:*'
              - 'codepipeline:GetPipeline'
              - 'codepipeline:CreatePipeline'
              - 'codepipeline:DeletePipeline'
              - 'codepipeline:GetPipelineState'
              - 'codepipeline:UpdatePipeline'
              - 'codebuild:CreateProject'
              - 'codebuild:UpdateProject'
              - 'codebuild:ListSourceCredentials'
              - 'cloudformation:CreateStack'
              - 'cloudformation:UpdateStack'
              - 'secretsmanager:GetSecretValue'
            Resource: '*'
      Users:
        - koyamaakira