AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for ALB
      GroupName: alb-sg
      SecurityGroupIngress:
        - CidrIp: '{{resolve:secretsmanager:my-ip:SecretString:my-ip}}'
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      VpcId: !ImportValue VPCOutput
      Tags:
        - Key: Name
          Value: alb-sg

Outputs:
  ALBSecurityGroupOutput:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: ALBSecurityGroupOutput