AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for VPC
      GroupName: vpc-sg
      VpcId: !ImportValue VPCOutput
      Tags:
        - Key: Name
          Value: vpc-sg

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for ALB
      GroupName: alb-sg
      VpcId: !ImportValue VPCOutput
      Tags:
        - Key: Name
          Value: alb-sg